services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000"
    environment: {}
    restart: unless-stopped
    # volumes:
    #   - ../../:/app  # Décommente pour le développement local si besoin

