version: "3.8"

services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000"
    environment:
      # Ajoute ici tes variables d'environnement si besoin
      # Exemple:
      # NODE_ENV: production
    restart: unless-stopped
    # volumes:
    #   - ../../:/app  # Décommente pour le développement local si besoin

